### ISSUE TITLE
java.lang.NoSuchMethodError: io.codetail.animation.SupportAnimator.setDuration

### ISSUE THREAD

**Issue by muhammad-naderi** [bowyer-app/fab-toolbar#7]
Hi,

calling `mFabToolbar.expandFab();` on pre lollipop device, causes following exception:

`java.lang.NoSuchMethodError: io.codetail.animation.SupportAnimator.setDuration
                                                                                  at com.bowyer.app.fabtoolbar.FabToolbar.expandPreLollipop(FabToolbar.java:368)
                                                                                  at com.bowyer.app.fabtoolbar.FabToolbar.expandFab(FabToolbar.java:241)
                                                                                  at com.shygunsys.mu.cybermobile.ui.MainActivityFragment$1.onClick(MainActivityFragment.java:61)`

**Comment by alirezabonab** [comment]
did you find any solution?

**Comment by muhammad-naderi** [comment]
nope

**Comment by bowyer-app** [comment]
Hi @muhammad-naderi 

You must write  'build.gradle' like this.

```
dependencies {
    compile 'com.bowyer.app:fab-toolbar:1.1.0@aar'
    compile 'com.github.ozodrukh:CircularReveal:1.1.1'
}
```

try it.

**Comment by Tsangares** [comment]
Thank you!

**Comment by Tsangares** [comment]
https://github.com/ozodrukh/CircularReveal
the dependency updated to 1.3.1
`dependencies {
        compile 'com.github.ozodrukh:CircularReveal:1.3.1'
    }`
